apiVersion: apps/v1
kind: Deployment
metadata:
  name: cce7days-app4-xiangxiaoc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cce7days-app4-xiangxiaoc
  template:
    metadata:
      labels:
        app: cce7days-app4-xiangxiaoc
    spec:
      containers:
      - name: cce7days-app4-xiangxiaoc
        image: nginx:latest
        resources: {}
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: default-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - 192.168.52.121
