apiVersion: v1
kind: Service
metadata:
  name: elastalert
  namespace: default
spec:
  selector:
    app: elastalert
  ports:
  - port: 3030
    targetPort: for-kibana
    name: for-kibana
  - port: 3333
    targetPort: websockets
    name: websockets