apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cce
  name: pod-reader
rules:
  - apiGroups:
      - "*"
    resources:
      - pod
    verbs:
      - get
      - watch
      - list