apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: cce
subjects:
  - kind: ServiceAccount
    name: cce-service-account
    namespace: cce
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader