apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowsocks
  labels:
    app: shadowsocks
spec:
  selector:
    matchLabels:
      app: shadowsocks
  template:
    metadata:
      labels:
        app: shadowsocks
    spec:
      containers:
      - name: shadowsocks
        image: shadowsocks/shadowsocks-libev
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8388
          protocol: TCP
        - containerPort: 8388
          protocol: UDP
        env:
          - name: METHOD
            value: aes-256-cfb
          - name: PASSWORD
            value: 9MLSpPmNt
          # - name: DNS_ADDRS
          #   value: 8.8.8.8,8.8.4.4