apiVersion: v1
kind: Service
metadata:
  name: shadowsocks
  labels:
    app: shadowsocks
spec:
  selector:
    app: shadowsocks
  ports:
  - port: 8388
    targetPort: 8388
    protocol: TCP
    nodePort: 31388
  - port: 8388
    targetPort: 8388
    protocol: UDP
    nodePort: 31388
  type: NodePort
