apiVersion: v1
kind: Pod
metadata:
  name: cce7days-app5-pod-xiangxiaoc
  labels:
    app: cce7days-app5-pod-xiangxiaoc
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.169.159
  containers:
  - name: cce7days-app5-pod-xiangxiaoc
    image: nginx:latest
    imagePullPolicy: Always
    resources: {}
    ports:
      - containerPort: 80
  restartPolicy: Always
  schedulerName: default-scheduler

