apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-head
  labels:
    app: elasticsearch-head
spec:
  selector:
    matchLabels:
      app: elasticsearch-head
  template:
    metadata:
      labels:
        app: elasticsearch-head
    spec:
      tolerations:
      - operator: "Exists"
      containers:
      - name: elasticsearch-head
        image: mobz/elasticsearch-head:5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"  
      
---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-head
  labels:
    app: elasticsearch-head
spec:
  selector:
    app: elasticsearch-head
  ports:
  - port: 9100
    targetPort: 9100
  type: NodePort