apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "0"
            cpu: "0"
        ports:
        - containerPort: 6379
        command:
          - redis-server
        args:
          - --appendonly yes
        volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
        - name: redis-data
          hostPath:
            path: /data/redis
            type: DirectoryOrCreate